### ISSUE TITLE
Sandvolleyball: Sett blir satt på 25 ikke 21. 

### ISSUE THREAD

**Issue by SindreSvendby** [oveien/BlussTV#1]
![set-ikke-satt-ved-settslutt](https://cloud.githubusercontent.com/assets/1047421/24072714/6f018b2e-0beb-11e7-8f82-f781f4786c4a.png)

Som man ser av bilde, så autoswitcher man poeng ved 21, men sett blir ikke satt.

Vi kjørte også 1 sett til 21 eller 3 sett til 15. 

Hadde en annen approche på dette problemet være og lage en liten settingsknapp, også skrev man inn antall sett, ved antall poeng settet var slutt, og antall poeng settet var slutt i siste sett? 
Dette tror jeg da hadde løst alle cases. Tenker også innendørs i rankingturneringer så har man jo ofte 3 settskamper, og man har jo eksprimentert internasjonalt med 5 eller 7 sett til 11.

**Comment by oveien** [comment]
Fiksa
