### ISSUE TITLE
Dokumentasjon - elite vs 1. div.

### ISSUE THREAD

**Issue by hansfn** [oveien/BlussTV#11]
Hei!

Skulle vi lagd noe dokumentasjon for bruk av tjenesten - enten som del av https://programvare.volleyball.no/volley-streaming-wiki/ eller i dette repoet?

Vi (SK Rival) har nettopp rykket opp til 1. divisjon og planlegger å bruke BlussTV for overlay i OBS. Det ser ut som det kun er elite som integrer mot Datavolley så vi skal velge "1. div og lavere" eller?

![image](https://github.com/oveien/BlussTV/assets/92755/4c8ec482-9fcd-4d94-a999-ad1ea74c8ee4)

Og masse andre små spørsmål antar jeg. Vi kan godt diskutere dette på Slack istedenfor, altså.

**Comment by tutturen** [comment]
Gratulerer med opprykk!

Det ser ut som at du har forstått det riktig.

Jeg har ikke så mye tid tilgjengelig til å bidra med det, men vi tar imot all hjelp med åpne armer!

**Comment by hansfn** [comment]
Fikk litt info på OSVB sin slack. Du godkjente #12 så dermed lukker jeg bare for nå.
