### ISSUE TITLE
Antagelse om fornavn og etternavn 

### ISSUE THREAD

**Issue by SindreSvendby** [oveien/BlussTV#2]
![navn forsvinner ved kun 1 navn](https://cloud.githubusercontent.com/assets/1047421/24072744/e75a9944-0beb-11e7-85fe-b01abce30731.png)

Teamnavnet kommer fra etternavnet, dette er jo egentlig en grei beslutning hvis man vet det. Men vi skrev inn bare et navn noen ganger, som førte til at det ble blankt. 
Nå tror jeg den tar alt etter siste mellomrom, men ved 0 mellomrom tror jeg den bare bør ta hele strengen!

"fornavn mellomnavn etternavn" funka bra

**Comment by oveien** [comment]
Fiksa
