### ISSUE TITLE
La appen bruke SVG-logoer

### ISSUE THREAD

**Issue by tutturen** [oveien/BlussTV#3]
Det ligger kode for å hente klubbilder (både png og svg) i `server.js`, men systemet som helhet virker ikke som det skal:

```javascript
router.get("/graphics/:club/logo.jpg",function(req,res) { //
    var safeClubName = sanitize(req.params.club);

    var clubDir = __dirname + '/data/' + safeClubName;
    var filename = clubDir + '/logo.jpg';

    var svgFilename = __dirname + "/app/graphics/logo/" + safeClubName.toLowerCase() + ".svg";
    console.log(svgFilename);
    if (fs.existsSync(svgFilename)) {
        filename = svgFilename;
    }
    console.log(filename);
    res.sendFile(filename);
});
```
For eksempel se for oss at vi skal hente logoen til Førde.
Svg-logoen til førde heter `forde.svg`, så vi kan enkelt spørre `/graphics/forde/logo.jpg`, og det virker - vi får en SVG.

Eneste problemet er at appen ellers ikke bruker den urlen for å hente logo til førde, den bruker `graphics/Førde%20VBK/logo.jpg`. Og der får vi en liten jpg med hvit bakgrunn.

**Comment by oveien** [comment]
Har endret slik at den for flere klubber får henta riktig svg, bla. Førde. Om ikke fallbacker den til logo fra poengliga.
